# Generated by Django 3.1.7 on 2021-04-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('length', models.IntegerField(max_length=50)),
                ('width', models.IntegerField(max_length=50)),
                ('hin', models.CharField(max_length=50)),
                ('service_interval', models.IntegerField(max_length=50)),
                ('next_service', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('seats', models.IntegerField(max_length=2)),
                ('color', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50)),
                ('current_mileage', models.IntegerField(max_length=50)),
                ('service_interval', models.IntegerField(max_length=50)),
                ('next_service', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('seats', models.IntegerField(max_length=2)),
                ('bed_length', models.IntegerField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50)),
                ('current_mileage', models.IntegerField(max_length=50)),
                ('service_interval', models.IntegerField(max_length=50)),
                ('next_service', models.IntegerField(max_length=50)),
            ],
        ),
    ]
