# Generated by Django 3.1.7 on 2021-04-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='next_service',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='service_interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='width',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='boat',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='current_mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='next_service',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='service_interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='bed_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='current_mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='next_service',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='service_interval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='truck',
            name='year',
            field=models.IntegerField(),
        ),
    ]
