# Generated by Django 3.1.7 on 2021-04-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210401_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='id',
        ),
        migrations.AlterField(
            model_name='boat',
            name='hin',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='truck',
            name='vin',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
