# Generated by Django 3.1.7 on 2021-04-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210401_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='current_hours',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
