# Generated by Django 3.1.7 on 2021-04-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210402_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='truck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
